import { createSlice } from '@reduxjs/toolkit';

export interface ModalState {
  isModalOpen: boolean;
}

const modalSlice = createSlice({
  name: 'modal',
  initialState: {
    isModalOpen: false,
  },
  reducers: {
    showModal: (state) => {
      state.isModalOpen = true;
    },
    hideModal: (state) => {
      state.isModalOpen = false;
    },
  },
});

// Export actions generated by createSlice
export const { showModal, hideModal } = modalSlice.actions;

// Export the reducer to be used in store configuration
export default modalSlice.reducer;
